trigger:
- main

resources:
  repositories:
    - repository: template
      type: git
      name: DevOps

pool:
  vmImage: ubuntu-latest

variables:
  major: '2'
  minor: '1'
  buildConfiguration: 'Release'

extends:
  template: build-nuget-package.yml@template
  parameters:
    solutionToBuild: 'Beis.HelpToGrow.Persistence.sln'
    projectToPublish: 'Beis.HelpToGrow.Persistence.csproj'
